name = 'v1'
compatibility_date = "2024-07-03"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AcYwAAIncDFkOWNkYzZmYzY1NDA0YjllYWM1ODNhYzdmZThiMWRkNnAxNTA3MzY"
UPSTASH_REDIS_REST_URL = "https://worthy-bullfrog-50736.upstash.io"